defaultRules:
  create: false


global:
  rbac:
    create: true
    pspEnabled: false

## Configuration for alertmanager
alertmanager:
  enabled: false

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: false
 
## Component scraping the kube api server
##
kubeApiServer:
  enabled: true

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: false

## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: true
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: false
    insecureSkipVerify: true

## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: false

## Component scraping etcd
##
kubeEtcd:
  enabled: false

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: true
  service:
    port: 10252
    targetPort: 10252
  serviceMonitor:
    https: true
    insecureSkipVerify: true


## Component scraping kube proxy
##
kubeProxy:
  enabled: false

## Component scraping kube state metrics
##
kubeStateMetrics:
  enabled: false

## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: false

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  image:
    tag: v0.58.0

## Deploy a Prometheus instance
##
prometheus:
  enabled: false
