apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "labels.common" . | indent 4 }}
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
