apiVersion: v2
appVersion: v2.36.1
name: prometheus-agent-app
description: A Helm chart for Prometheus agent.
home: https://github.com/giantswarm/prometheus-agent-app
sources:
  - https://github.com/giantswarm/prometheus-agent-app
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: atlas
  branch: main
