image: 
  registry: quay.io
  name: giantswarm/prometheus
  tag: ""

remoteWrite: []

probeNamespaceSelector: {}
probeSelector:
  matchLabels:
    app: prometheus-agent
serviceMonitorSelector: {}
podMonitorSelector:
  matchLabels:
    app: prometheus-agent
serviceMonitorNamespaceSelector: {}
podMonitorNamespaceSelector: {}

securityContext:
  fsGroup: 2000
  runAsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
