apiVersion: v2
appVersion: v2.41.0
name: prometheus-agent
description: A Helm chart for Prometheus agent.
home: https://github.com/giantswarm/prometheus-agent-app
sources:
  - https://github.com/giantswarm/prometheus-agent-app
version: v0.1.0
annotations:
  application.giantswarm.io/team: atlas
