global:
  image:
    registry: gsoci.azurecr.io

image:
  name: giantswarm/prometheus
  tag: ""
  sha: ""
  pullPolicy: "Always"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: karpenter.sh/capacity-type
          operator: NotIn
          values:
          - spot
      weight: 100
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: operator.prometheus.io/name
            operator: In
            values:
            - prometheus-agent
        topologyKey: kubernetes.io/hostname
      weight: 50

keepDroppedTargets: 0

remoteWrite: []
# - name: ""     # Name of the remote write integration
#   proxyUrl: ""
#   url: ""      # URL to send data to
#   username: "" # Username to use
#   password: "" # Password
#   enableHTTP2: false
#   # https://github.com/prometheus-community/prometheus-operator/blob/main/Documentation/api.md#queueconfig
#   queueConfig:
#     capacity: 30000
#     maxSamplesPerSend: 10000
#     maxShards: 10
#   remoteTimeout: 60
#   tlsConfig:
#     insecureSkipVerify: false

replicas: 1
shards: 1

retention: 10d

externalLabels: {}

serviceMonitor:
  enabled: true
  jobLabel: prometheus-agent
  ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
  ##
  metricRelabelings: []
  # - action: keep
  #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
  #   sourceLabels: [__name__]

  ## RelabelConfigs to apply to samples before scraping
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
  ##
  relabelings: []
  # - sourceLabels: [__meta_kubernetes_pod_node_name]
  #   separator: ;
  #   regex: ^(.*)$
  #   targetLabel: nodename
  #   replacement: $1
  #   action: replace

priorityClassName: giantswarm-critical

probeNamespaceSelector: {}
probeSelector: {}
serviceMonitorNamespaceSelector: {}
serviceMonitorSelector: {}
podMonitorNamespaceSelector: {}
podMonitorSelector: {}

# scrapeClasses allows to define relabelings for specific scrape classes that can be used in ServiceMonitors and PodMonitors.
# More info: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ScrapeClass
scrapeClasses: []
# defaultScrapeClasses is the Giant Swarm scrape classes that can be used in GS ServiceMonitors and PodMonitors.
defaultScrapeClasses:
  - name: giantswarm-default
    default: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: "replace"
      targetLabel: app
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      action: "replace"
      targetLabel: node

scrapeInterval: 60s

securityContext:
  fsGroup: 2000
  runAsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

psp:
  enabled: true

watchdog:
  enabled: true
  overloadTolerance: 5
  probeTimeout: 3
  probeRetries: 3
  # command:
  #   - sh
  #   - /etc/prometheus/configmaps/prometheus-agent-watchdog/watchdog.sh

configmaps:
  - prometheus-agent-watchdog
