---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-watchdog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
binaryData:
  watchdog.sh: |-
    {{ .Files.Get "files/watchdog.sh" | b64enc }}
