{{- $remoteWrites := concat .Values.global.remoteWrite .Values.remoteWrite -}}
{{- $externalLabels := merge .Values.global.externalLabels .Values.externalLabels -}}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    {{ include "labels.common" . | nindent 4 }}
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: operator.prometheus.io/name
              operator: In
              values:
              - prometheus-agent
  containers:
  - args:
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.agent.path=/prometheus
    - --enable-feature=agent
    - --web.enable-lifecycle
    - --web.listen-address=:9090
    name: prometheus
    # force exposition of port for monitoring
    ports:
    - containerPort: 9090
      name: http-web
      protocol: TCP
    {{- if .Values.watchdog.enabled }}
    lifecycle:                                                                                                                                                                                                                                                
      preStop:                                                                                                                                                                                                                                                
        exec:                                                                                                                  
          command:                                                                                                             
          - /bin/sh                                                                                                            
          - -c                                                                                                                 
          - rm -rf /prometheus/wal
    livenessProbe:
      exec:
        command:
        {{- if .Values.watchdog.command }}
        {{- toYaml .Values.watchdog.command | nindent 8 }}
        {{- else }}
        - sh
        - /etc/prometheus/configmaps/prometheus-agent-watchdog/watchdog.sh
        {{- end }}
    {{- end }}
  configMaps:
    {{- toYaml .Values.configmaps | nindent 4 }}
  enableFeatures:
  - agent
  {{- if $externalLabels }}
  externalLabels:
    {{- toYaml $externalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.image.sha }}
  image: "{{ .Values.global.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.image.sha }}"
  {{- else }}
  image: "{{ .Values.global.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- end }}
  # workaround - required to use an `exec command` livenessProbe.
  listenLocal: true
  podMetadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    labels:
      {{ include "labels.common" . | nindent 6 }}
{{- if .Values.podMonitorNamespaceSelector }}
  podMonitorNamespaceSelector:
    {{- toYaml  .Values.podMonitorNamespaceSelector | nindent 4 }}
{{ else }}
  podMonitorNamespaceSelector: {}
{{- end }}
{{- if .Values.podMonitorSelector }}  
  podMonitorSelector:
    {{- toYaml  .Values.podMonitorSelector | nindent 4 }}
{{- else }}
  podMonitorSelector: {}
{{- end }}
  portName: http-web
{{- if .Values.probeNamespaceSelector }}  
  probeNamespaceSelector:
    {{- toYaml  .Values.probeNamespaceSelector | nindent 4 }}
{{- else }}
  probeNamespaceSelector: {}
{{- end }}
{{- if .Values.probeSelector }}
  probeSelector:
    {{- toYaml  .Values.probeSelector | nindent 4 }}
{{- else }}
  probeSelector: {}
{{- end }}
  prometheusExternalLabelName: ""
{{- if $remoteWrites }}
  remoteWrite:
  {{- range $remoteWrite := $remoteWrites }}
  - basicAuth:
      password:
        key: password
        name: {{ $remoteWrite.name }}-remote-write-api
      username:
        key: username
        name: {{ $remoteWrite.name }}-remote-write-api
    name: {{ $remoteWrite.name }}
    {{- if $remoteWrite.proxyUrl }}
    proxyUrl: {{ $remoteWrite.proxyUrl }}
    {{- end }}
    remoteTimeout: 30s
    url: {{ $remoteWrite.url }}
{{- if $remoteWrite.tlsConfig }}
    tlsConfig:
      {{- toYaml $remoteWrite.tlsConfig | nindent 6 }}
{{- end }}
{{- if $remoteWrite.queueConfig }}
    queueConfig:
      {{- toYaml $remoteWrite.queueConfig | nindent 6 }}
{{- end -}}
{{- end -}}
{{- else }}
  remoteWrite: []
{{- end }}
  replicas: {{ .Values.replicas }}
  replicaExternalLabelName: ""
  retention: {{ .Values.retention }}
  scrapeInterval: {{ .Values.scrapeInterval }}
  securityContext:
    {{- toYaml  .Values.securityContext | nindent 4 }}
  serviceAccountName: {{ include "name" .}}
{{- if .Values.serviceMonitorNamespaceSelector }}
  serviceMonitorNamespaceSelector:
    {{- toYaml .Values.serviceMonitorNamespaceSelector | nindent 4 }}
{{- else }}
  serviceMonitorNamespaceSelector: {}
{{- end }}
{{- if .Values.serviceMonitorSelector }}
  serviceMonitorSelector:
    {{- toYaml .Values.serviceMonitorSelector | nindent 4 -}}
{{ else }}
  serviceMonitorSelector: {}
{{- end }}
  shards: {{ .Values.shards }}
  version: {{ default .Values.image.tag .Values.version | default .Chart.AppVersion }}
