{{- $remoteWrites := concat .Values.global.remoteWrite .Values.remoteWrite -}}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    {{ include "labels.common" . | nindent 4 }}
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.agent.path=/prometheus
    - --enable-feature=agent
    - --web.enable-lifecycle
    - --web.listen-address=:9090
    name: prometheus
  enableFeatures:
  - agent
  {{- if .Values.image.sha }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.image.sha }}"
  {{- else }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- end }}
  listenLocal: false
{{- if .Values.podMonitorNamespaceSelector }}
    {{ toYaml  .Values.podMonitorNamespaceSelector | nindent 4 }}
{{ else }}
  podMonitorNamespaceSelector: {}
{{- end }}
{{- if .Values.podMonitorSelector }}  
  podMonitorSelector:
    {{- toYaml  .Values.podMonitorSelector | nindent 4 }}
{{- else }}
  podMonitorSelector: {}
{{- end }}
  portName: http-web
{{- if .Values.probeNamespaceSelector }}  
  probeNamespaceSelector:
    {{- toYaml  .Values.probeNamespaceSelector | nindent 4 }}
{{- else }}
  probeNamespaceSelector: {}
{{- end }}
{{- if .Values.probeSelector }}
  probeSelector:
    {{- toYaml  .Values.probeSelector | nindent 4 }}
{{- else }}
  probeSelector: {}
{{- end }}
{{- if $remoteWrites }}
  remoteWrite:
  {{- range $remoteWrite := $remoteWrites }}
  - basicAuth:
      password:
        key: password
        name: {{ $remoteWrite.name }}-remote-write-api
      username:
        key: username
        name: {{ $remoteWrite.name }}-remote-write-api
    remoteTimeout: 5m
    url: {{ $remoteWrite.url }}
{{- if $remoteWrite.queueConfig }}
    queueConfig:
      {{- toYaml $remoteWrite.queueConfig | nindent 6 }}
{{- end -}}
{{- end -}}
{{- else }}
  remoteWrite: []
{{- end }}
  retention: 10d
  securityContext:
    {{- toYaml  .Values.securityContext | nindent 4 }}
  serviceAccountName: {{ include "name" .}}
{{- if .Values.serviceMonitorNamespaceSelector }}
  serviceMonitorNamespaceSelector:
    {{- toYaml .Values.serviceMonitorNamespaceSelector | nindent 4 }}
{{- else }}
  serviceMonitorNamespaceSelector: {}
{{- end }}
{{- if .Values.serviceMonitorSelector }}
  serviceMonitorSelector:
    {{- toYaml .Values.serviceMonitorSelector | nindent 4 -}}
{{ else }}
  serviceMonitorSelector: {}
{{- end }}
  podMetadata:
    labels:
      {{ include "labels.common" . | nindent 6 }}
  version: {{ .Values.image.tag | default .Chart.AppVersion }}
