{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
{{ if .Values.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "psp.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "name"  . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "psp.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
