{{- $remoteWrites := concat .Values.global.remoteWrite .Values.remoteWrite -}}
{{- range $remoteWrite := $remoteWrites -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $remoteWrite.name }}-remote-write-api
  namespace: {{ $.Release.Namespace }}
stringData:
  username: {{ $remoteWrite.username }}
  password: {{ $remoteWrite.password }}
{{ end }}
