{{- if and .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{ include "labels.common" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - interval: {{ .Values.scrapeInterval }}
    port: web
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | nindent 4) . }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{ tpl (toYaml .Values.serviceMonitor.relabelings | nindent 4) . }}
    {{- end }}
  - interval: {{ .Values.scrapeInterval }}
    port: reloader-web
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | nindent 4) . }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{ tpl (toYaml .Values.serviceMonitor.relabelings | nindent 4) . }}
    {{- end }}
{{- end }}
