global:
  remoteWrite: []
  # - name: ""     # Name of the remote write integration
  #   url: ""      # URL to send data to
  #   username: "" # Username to use
  #   password: "" # Password
  #   #  https://github.com/prometheus-community/prometheus-operator/blob/main/Documentation/api.md#queueconfig
  #   queueConfig:
  #     capacity: 10000
  #     maxSamplesPerSend: 1000
  #     minShards: 10

prometheus-agent:
  image:
    registry: quay.io
    name: giantswarm/prometheus
    tag: ""
    sha: ""
    pullPolicy: "Always"

  remoteWrite: []
  # - name: ""     # Name of the remote write integration
  #   url: ""      # URL to send data to
  #   username: "" # Username to use
  #   password: "" # Password
  #   #   https://github.com/prometheus-community/prometheus-operator/blob/main/Documentation/api.md#queueconfig
  #   queueConfig:
  #     capacity: 10000
  #     maxSamplesPerSend: 1000
  #     minShards: 10

  probeNamespaceSelector: {}
  probeSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  psp:
    enabled: true
