global:
  image:
    registry: docker.io
  remoteWrite: []
  # - name: ""     # Name of the remote write integration
  #   url: ""      # URL to send data to
  #   username: "" # Username to use
  #   password: "" # Password
  #   #  https://github.com/prometheus-community/prometheus-operator/blob/main/Documentation/api.md#queueconfig
  #   queueConfig:
  #     capacity: 10000
  #     maxSamplesPerSend: 1000
  #     minShards: 10

  externalLabels: {}

prometheus-agent:
  image:
    name: giantswarm/prometheus
    tag: ""
    sha: ""
    pullPolicy: "Always"

  remoteWrite: []
  # - name: ""     # Name of the remote write integration
  #   proxyUrl: ""
  #   url: ""      # URL to send data to
  #   username: "" # Username to use
  #   password: "" # Password
  #   #   https://github.com/prometheus-community/prometheus-operator/blob/main/Documentation/api.md#queueconfig
  #   queueConfig:
  #     capacity: 30000
  #     maxSamplesPerSend: 10000
  #     maxShards: 10
  #   tlsConfig:
  #     insecureSkipVerify: false

  replicas: 1
  shards: 1

  retention: 10d

  externalLabels: {}

  version: ""

  serviceMonitor:
    enabled: true

    ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

    ## RelabelConfigs to apply to samples before scraping
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    relabelings:
      # Add app label.
      - sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        targetLabel: app
      # Add instance label.
      - sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_instance
        targetLabel: instance
      # Add node label.
      - sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: node
      # Add team label.
      - sourceLabels:
        - __meta_kubernetes_pod_label_application_giantswarm_io_team
        targetLabel: team
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

  priorityClassName: giantswarm-critical

  probeNamespaceSelector: {}
  probeSelector:
    matchExpressions:
      - key: "application.giantswarm.io/team"
        operator: "Exists"
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchExpressions:
      - key: "application.giantswarm.io/team"
        operator: "Exists"
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchExpressions:
      - key: "application.giantswarm.io/team"
        operator: "Exists"

  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  psp:
    enabled: true

  watchdog:
    enabled: true
    watchdogOverloadTolerance: 5
    # command:
    #   - sh
    #   - /etc/prometheus/configmaps/prometheus-agent-watchdog/watchdog.sh
