prometheus-agent:
  image:
    registry: quay.io
    name: giantswarm/prometheus
    tag: ""
    sha: ""
    pullPolicy: "Always"

  remoteWrite: []
  # - name: ""     # Name of the remote write integration
  #   url: ""      # URL to send data to
  #   username: "" # Username to use
  #   password: "" # Password

  probeNamespaceSelector: {}
  probeSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  psp:
    enabled: true
