image:
  registry: quay.io
  name: giantswarm/prometheus
  tag: ""
  sha: ""
  pullPolicy: "Always"

remoteWrite: []

probeNamespaceSelector: {}
probeSelector:
  matchLabels:
    app: prometheus-agent
serviceMonitorNamespaceSelector: {}
serviceMonitorSelector: {}
podMonitorNamespaceSelector: {}
podMonitorSelector:
  matchLabels:
    app: prometheus-agent

securityContext:
  fsGroup: 2000
  runAsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

psp:
  enabled: true
