apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
     resource: Prometheus
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.agent.path=/prometheus
    - --enable-feature=agent
    - --web.enable-lifecycle
    - --web.listen-address=:9090
    name: prometheus
  enableAdminAPI: false
  enableFeatures:
  - agent
  evaluationInterval: 30s
  externalUrl: {{ include "external-url" .}}
  image: {{ include "prometheus-image" . }}
  listenLocal: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
{{ toYaml  .Values.labelSelector | indent 6 }}
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
{{ toYaml  .Values.labelSelector | indent 6 }}
  remoteWrite:
{{ toYaml .Values.remoteWrite | indent 2 }}
  retention: 10d
  routePrefix: /
  scrapeInterval: 30s
  securityContext:
{{ toYaml  .Values.securityContext | indent 4 }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
{{ toYaml  .Values.labelSelector | indent 6 }}
  version: {{ .Chart.AppVersion }}
