apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "labels.common" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 9090
    targetPort: http-web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: ClientIP
